(function(){
  const BASE='https://mirpanel.com';
  const DEFAULT_TITLE='Mirpanel - Premium Hesablar Azərbaycan';
  const DEFAULT_DESC='Netflix, Spotify, CapCut Pro, ChatGPT Plus, Canva, YouTube Premium və digər premium hesabları Azərbaycanda sərfəli qiymətə əldə et.';
  const DEFAULT_IMG=BASE+'/assets/logo.png';
  const COMMON=['premium hesab almaq','ucuz premium hesab','premium hesab Azərbaycan','premium hesab Bakı','premium abunə almaq','ucuz abunə almaq','aylıq premium hesab','premium hesab aktivləşdirmə','hazır premium hesab','etibarlı premium hesab','ucuz hesab almaq','hesab almaq Azərbaycan','premium paket almaq','rəqəmsal hesab almaq','online hesab almaq','WhatsApp ilə premium hesab almaq'];
  const SEO={
    capcut:{slug:'capcut-pro-almaq',title:'CapCut Pro almaq | Premium video montaj hesabı - Mirpanel',desc:'CapCut Pro hesabını Azərbaycanda sərfəli qiymətə əldə et. Premium effektlər, 4K eksport və WhatsApp ilə rahat sifariş.',kw:['CapCut Pro almaq','CapCut Pro ucuz','CapCut Pro qiyməti','CapCut Pro Azərbaycan','CapCut Pro Bakı','CapCut Pro hesab almaq','CapCut Pro aylıq','CapCut Pro hazır hesab','CapCut Pro aktivləşdirmə','CapCut Pro premium almaq'],text:'CapCut Pro almaq istəyənlər üçün Mirpanel Azərbaycanda sürətli aktivləşdirmə və rahat WhatsApp sifarişi təqdim edir.'},
    netflix:{slug:'netflix-sexsi-almaq',aliases:['netflix-almaq','netflix-aile-almaq'],title:'Netflix almaq | Ucuz Netflix Premium Azərbaycan - Mirpanel',desc:'Netflix Premium hesabını Azərbaycanda sərfəli qiymətə əldə et. Şəxsi profil, sürətli aktivləşdirmə və WhatsApp ilə rahat sifariş.',kw:['Netflix almaq','Netflix Premium almaq','Netflix ucuz almaq','Netflix qiyməti','Netflix Azərbaycan','Netflix Bakı','Netflix hesab almaq','Netflix aylıq','Netflix hazır hesab','Netflix aktivləşdirmə','Netflix şəxsi hesab','Netflix şəxsi almaq','Netflix ümumi hesab','Netflix ailə hesabı','Netflix ucuz Azərbaycan','Netfilix almaq','Netflex almaq'],text:'Netflix almaq üçün Mirpanel ucuz Netflix Premium paketlərini, şəxsi profil sifarişini və etibarlı aktivləşdirməni təqdim edir.'},
    netflix_umumi:{slug:'netflix-umumi-almaq',title:'Netflix Ümumi almaq | Ucuz Netflix hesab - Mirpanel',desc:'Netflix ümumi profil hesabını sərfəli qiymətə al. Azərbaycanda Netflix Premium paketləri və sürətli WhatsApp sifarişi.',kw:['Netflix ümumi hesab','Netflix ümumi almaq','Netflix almaq','Netflix ucuz almaq','Netflix Premium qiyməti'],text:'Netflix Ümumi hesab Mirpanel-də sərfəli qiymətə təqdim olunur.'},
    spotify:{slug:'spotify-premium-almaq',title:'Spotify Premium almaq | Ucuz Spotify hesab - Mirpanel',desc:'Spotify Premium hesabını Azərbaycanda ucuz qiymətə əldə et. Reklamsız musiqi, şəxsi hesab və sürətli aktivləşdirmə.',kw:['Spotify almaq','Spotify Premium almaq','Spotify ucuz','Spotify qiyməti','Spotify Azərbaycan','Spotify hesab almaq','Spotify aylıq','Spotify aktivləşdirmə','Spotify Premium ucuz','Spotify reklamsız almaq','Spotfy almaq'],text:'Spotify Premium almaq istəyənlər üçün Mirpanel reklamsız musiqi və rahat dinləmə təcrübəsi təqdim edən premium hesabları aktivləşdirir.'},
    prime:{slug:'amazon-prime-video-almaq',aliases:['prime-video-almaq'],title:'Amazon Prime Video almaq | Prime Video ucuz - Mirpanel',desc:'Amazon Prime Video hesabını Azərbaycanda sərfəli qiymətə al. Film və seriallar üçün Prime Video premium hesabı.',kw:['Amazon Prime Video almaq','Prime Video almaq','Amazon Prime almaq','Amazon Prime ucuz','Prime Video ucuz','Prime Video qiyməti'],text:'Amazon Prime Video almaq üçün Mirpanel Prime Video hesablarını sərfəli qiymətlə təqdim edir.'},
    hbomax:{slug:'hbo-max-almaq',title:'HBO Max almaq | Ucuz HBO Max hesab Azərbaycan - Mirpanel',desc:'HBO Max hesabını Azərbaycanda sərfəli qiymətə al. Premium film və serial izləmə üçün sürətli aktivləşdirmə.',kw:['HBO Max almaq','HBO Max ucuz','HBO Max qiyməti','HBO Max Azərbaycan','HBO Max hesab almaq','HBO Max aylıq'],text:'HBO Max almaq istəyənlər üçün Mirpanel film və serial izləmə hesablarını Azərbaycanda sərfəli qiymətə təqdim edir.'},
    youtube:{slug:'youtube-premium-almaq',title:'YouTube Premium almaq | Ucuz YouTube hesab - Mirpanel',desc:'YouTube Premium hesabını Azərbaycanda ucuz qiymətə əldə et. Reklamsız YouTube və YouTube Music üçün premium paket.',kw:['YouTube Premium almaq','YouTube Premium ucuz','YouTube Premium qiyməti','YouTube Premium Azərbaycan','YouTube reklamsız almaq','Yutub premium almaq'],text:'YouTube Premium almaq üçün Mirpanel reklamsız video izləmə və YouTube Music imkanları olan premium hesabları təqdim edir.'},
    surfshark:{slug:'surfshark-vpn-almaq',title:'Surfshark VPN almaq | Ucuz VPN Azərbaycan - Mirpanel',desc:'Surfshark VPN hesabını sərfəli qiymətə al. Premium VPN, təhlükəsiz bağlantı və rahat aktivləşdirmə.',kw:['Surfshark VPN almaq','Surfshark almaq','VPN almaq','ucuz VPN almaq','VPN Azərbaycan'],text:'Surfshark VPN almaq istəyənlər üçün Mirpanel premium VPN hesablarını sərfəli qiymətə təqdim edir.'},
    tiktok_jeton:{slug:'tiktok-jeton-almaq',title:'TikTok Jeton almaq | Ucuz TikTok coin Azərbaycan - Mirpanel',desc:'TikTok Jeton və coin balansını Azərbaycanda sərfəli qiymətə artır. TikTok live hədiyyələri üçün rahat sifariş.',kw:['TikTok Jeton almaq','TikTok jeton ucuz','TikTok coin almaq','TikTok balans artırmaq'],text:'TikTok Jeton almaq və TikTok coin balansını artırmaq üçün Mirpanel sürətli sifariş imkanı təqdim edir.'},
    google_ai:{slug:'google-ai-pro-v3-almaq',aliases:['gemini-pro-almaq'],title:'Google AI Pro V3 almaq | Gemini Pro hesab - Mirpanel',desc:'Google AI Pro və Gemini Pro hesabını Azərbaycanda sərfəli qiymətə al. AI premium hesab üçün rahat sifariş.',kw:['Google AI Pro almaq','Google AI Pro V3 almaq','Gemini Pro almaq','Google Gemini Azərbaycan'],text:'Google AI Pro V3 və Gemini Pro almaq üçün Mirpanel AI premium hesabları təqdim edir.'},
    google_ai_ultra:{slug:'google-ai-pro-ultra-almaq',aliases:['gemini-ultra-almaq'],title:'Google AI Pro Ultra almaq | Gemini Ultra hesab - Mirpanel',desc:'Google AI Ultra və Gemini Ultra hesabını sərfəli qiymətə əldə et. Premium AI imkanları üçün Mirpanel.',kw:['Google AI Pro Ultra almaq','Google Gemini Ultra almaq','Gemini Ultra almaq'],text:'Google AI Pro Ultra almaq istəyən istifadəçilər üçün Mirpanel premium AI hesablarını təqdim edir.'},
    captions:{slug:'captions-ai-almaq',title:'Captions AI almaq | AI video montaj hesabı - Mirpanel',desc:'Captions AI Pro hesabını Azərbaycanda sərfəli qiymətə al. AI video montaj və premium hesab aktivləşdirmə.',kw:['Captions AI almaq','Captions AI Pro almaq','AI video montaj almaq'],text:'Captions AI almaq üçün Mirpanel süni intellekt dəstəkli video montaj hesablarını təqdim edir.'},
    grok_supergrok:{slug:'super-grok-ai-almaq',aliases:['grok-ai-almaq'],title:'Grok AI almaq | Super Grok AI hesab - Mirpanel',desc:'Grok AI və Super Grok hesabını Azərbaycanda sərfəli qiymətə əldə et. AI premium hesab sifarişi.',kw:['Grok AI almaq','Super Grok AI almaq','X AI Grok almaq'],text:'Grok AI və Super Grok AI almaq istəyənlər üçün Mirpanel AI premium hesab sifarişini rahatlaşdırır.'},
    claude_ai:{slug:'cloud-ai-pro-almaq',aliases:['cloud-ai-max-almaq','claude-ai-almaq'],title:'Cloud AI Pro almaq | AI premium hesab - Mirpanel',desc:'Cloud AI Pro və AI premium hesablarını Azərbaycanda sərfəli qiymətə əldə et. Mirpanel ilə sürətli aktivləşdirmə.',kw:['Cloud AI Pro almaq','Cloud AI Max almaq','AI hesab almaq','Claude AI almaq'],text:'Cloud AI Pro və AI premium hesab almaq üçün Mirpanel sərfəli rəqəmsal hesab sifarişi təqdim edir.'},
    zoom:{slug:'zoom-pro-almaq',title:'Zoom Pro almaq | Ucuz Zoom hesab Azərbaycan - Mirpanel',desc:'Zoom Pro hesabını Azərbaycanda sərfəli qiymətə al. Limitsiz görüş və premium meeting hesabı üçün Mirpanel.',kw:['Zoom Pro almaq','Zoom Pro ucuz','Zoom görüş hesabı','Zoom limitsiz görüş'],text:'Zoom Pro almaq istəyənlər üçün Mirpanel premium görüş hesablarını sərfəli qiymətə təqdim edir.'},
    duolingo:{slug:'duolingo-super-almaq',title:'Duolingo Super almaq | Duolingo Premium ucuz - Mirpanel',desc:'Duolingo Super hesabını Azərbaycanda ucuz qiymətə əldə et. Dil öyrənmə üçün premium hesab.',kw:['Duolingo Super almaq','Duolingo Premium almaq','Duolingo dil öyrənmə'],text:'Duolingo Super almaq istəyənlər üçün Mirpanel dil öyrənmə premium hesablarını təqdim edir.'},
    canva:{slug:'canva-premium-almaq',aliases:['canva-pro-almaq'],title:'Canva Premium almaq | Canva Pro ucuz qiymətə - Mirpanel',desc:'Canva Premium və Canva Pro hesabını Azərbaycanda sərfəli qiymətə əldə et. Dizayn üçün premium hesab.',kw:['Canva Premium almaq','Canva Pro almaq','Canva ucuz','Kanva almaq'],text:'Canva Premium almaq və Canva Pro hesabından istifadə etmək üçün Mirpanel dizayn hesablarını təqdim edir.'},
    chatgpt:{slug:'chatgpt-plus-almaq',title:'ChatGPT Plus almaq | Ucuz ChatGPT hesab Azərbaycan - Mirpanel',desc:'ChatGPT Plus hesabını Azərbaycanda sərfəli qiymətə əldə et. GPT və OpenAI premium hesab sifarişi.',kw:['ChatGPT Plus almaq','ChatGPT Plus ucuz','ChatGPT Plus Azərbaycan','GPT Plus almaq','OpenAI hesab almaq','ÇatGPT almaq'],text:'ChatGPT Plus almaq istəyənlər üçün Mirpanel OpenAI premium hesab sifarişini rahatlaşdırır.'},
    adobecc:{slug:'adobe-creative-cloud-almaq',aliases:['adobe-cc-almaq'],title:'Adobe Creative Cloud almaq | Adobe CC ucuz - Mirpanel',desc:'Adobe Creative Cloud hesabını Azərbaycanda sərfəli qiymətə al. Photoshop, Illustrator, Premiere Pro və digər Adobe proqramları.',kw:['Adobe Creative Cloud almaq','Adobe CC almaq','Photoshop almaq','Illustrator almaq','Adobe paket almaq'],text:'Adobe Creative Cloud almaq üçün Mirpanel Adobe proqram hesablarını sərfəli qiymətə təqdim edir.'}
  };
  function products(){try{if(typeof DATA!=='undefined'&&Array.isArray(DATA.products))return DATA.products}catch{}return Array.isArray(window.DATA?.products)?window.DATA.products:[]}
  function byId(id){return products().find(p=>p.id===id)}
  function slug(v){return String(v||'').trim().toLowerCase().replace(/[əƏ]/g,'e').replace(/[ıİ]/g,'i').replace(/[öÖ]/g,'o').replace(/[üÜ]/g,'u').replace(/[şŞ]/g,'s').replace(/[çÇ]/g,'c').replace(/[ğĞ]/g,'g').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
  function profile(p){return SEO[p?.id]||{}}
  function seoFor(p){const pr=profile(p), name=p?.title||'Premium hesab', kws=String(p?.seoKeywords||'').split(',').map(x=>x.trim()).filter(Boolean);return{slug:slug(p?.seoSlug||pr.slug||`${name}-almaq`),title:String(p?.seoTitle||pr.title||`${name} almaq | Premium hesab - Mirpanel`),description:String(p?.seoDescription||pr.desc||`${name} hesabını Azərbaycanda sərfəli qiymətə əldə et. Mirpanel ilə sürətli aktivləşdirmə və WhatsApp sifarişi.`),keywords:[...new Set([...(kws.length?kws:(pr.kw||[])),...COMMON])],content:String(p?.seoContent||pr.text||`${name} almaq üçün Mirpanel premium hesab və rəqəmsal xidmətləri sərfəli qiymətə təqdim edir.`)}}
  function productPath(p){return'/'+seoFor(p).slug}
  function productUrl(p){return BASE+productPath(p)}
  function productIdFromPath(path=location.pathname){const s=slug(String(path).replace(/^\/+|\/+$/g,''));if(!s)return'';const map=new Map;products().forEach(p=>{const pr=profile(p);[seoFor(p).slug,p.seoSlug,pr.slug,...(pr.aliases||[])].map(slug).filter(Boolean).forEach(x=>map.set(x,p.id))});return map.get(s)||''}
  function abs(src){try{return new URL(src||'/assets/logo.png',BASE).href}catch{return DEFAULT_IMG}}
  function meta(name,content,attr='name'){let e=document.head.querySelector(`meta[${attr}="${name}"]`);if(!e){e=document.createElement('meta');e.setAttribute(attr,name);document.head.appendChild(e)}e.setAttribute('content',content||'')}
  function canonical(url){let e=document.head.querySelector('link[rel="canonical"]');if(!e){e=document.createElement('link');e.rel='canonical';document.head.appendChild(e)}e.href=url}
  function ld(id,obj){let s=document.getElementById(id);if(!s){s=document.createElement('script');s.type='application/ld+json';s.id=id;document.head.appendChild(s)}s.textContent=JSON.stringify(obj)}
  function minPrice(p){const a=(p?.plans||[]).map(x=>Number(x.price)).filter(x=>x>0);return a.length?Math.min(...a):0}
  function availability(p){const raw=p?.stock??p?.stockCount??p?.stockQuantity;if(p?.stockEnabled===true&&raw!==null&&raw!==''&&raw!==undefined&&Number(raw)<=0)return'https://schema.org/OutOfStock';if(p?.soldOut||p?.flow==='out_of_stock')return'https://schema.org/OutOfStock';return'https://schema.org/InStock'}
  function homeSEO(){document.title=DEFAULT_TITLE;meta('description',DEFAULT_DESC);meta('keywords',COMMON.join(', '));canonical(BASE+'/');meta('og:title',DEFAULT_TITLE,'property');meta('og:description',DEFAULT_DESC,'property');meta('og:image',DEFAULT_IMG,'property');meta('og:url',BASE+'/','property');meta('og:type','website','property');meta('twitter:card','summary_large_image');meta('twitter:title',DEFAULT_TITLE);meta('twitter:description',DEFAULT_DESC);meta('twitter:image',DEFAULT_IMG);document.getElementById('mirpanel-product-schema')?.remove();ld('mirpanel-website-schema',{'@context':'https://schema.org','@graph':[{'@type':'Organization',name:'Mirpanel',url:BASE+'/',logo:DEFAULT_IMG},{'@type':'WebSite',name:'Mirpanel',url:BASE+'/',potentialAction:{'@type':'SearchAction',target:BASE+'/?q={search_term_string}','query-input':'required name=search_term_string'}}]})}
  function html(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function visible(p,s){const view=document.getElementById('productPageView');if(!view)return;let box=document.getElementById('productSeoContent');if(!box){box=document.createElement('section');box.id='productSeoContent';box.className='productSeoContent pp-bottom-section';view.appendChild(box)}box.innerHTML=`<h2>${html(p.title)} haqqında SEO məlumatı</h2><p>${html(s.content)}</p>`}
  function productSEO(pOrId){const p=typeof pOrId==='string'?byId(pOrId):pOrId;if(!p)return homeSEO();const s=seoFor(p),url=productUrl(p),img=abs(p.image),price=minPrice(p);document.title=s.title;meta('description',s.description);meta('keywords',s.keywords.join(', '));canonical(url);meta('og:title',s.title,'property');meta('og:description',s.description,'property');meta('og:image',img,'property');meta('og:url',url,'property');meta('og:type','product','property');meta('twitter:card','summary_large_image');meta('twitter:title',s.title);meta('twitter:description',s.description);meta('twitter:image',img);ld('mirpanel-product-schema',{'@context':'https://schema.org','@type':'Product',name:p.title,description:s.description,image:img,brand:{'@type':'Brand',name:'Mirpanel'},offers:{'@type':'Offer',price:price||undefined,priceCurrency:'AZN',availability:availability(p),url}});visible(p,s)}
  function style(){if(document.getElementById('mirpanel-seo-style'))return;const st=document.createElement('style');st.id='mirpanel-seo-style';st.textContent='.productSeoContent{margin-top:18px;padding:22px;border:1px solid rgba(255,212,0,.18);border-radius:18px;background:rgba(10,10,10,.72);box-shadow:0 18px 42px rgba(0,0,0,.22)}.productSeoContent h2{margin:0 0 10px;color:#ffd400;font-size:20px}.productSeoContent p{margin:0;color:rgba(255,255,255,.82);line-height:1.65}@media(max-width:640px){.productSeoContent{margin-top:14px;padding:16px;border-radius:14px}.productSeoContent h2{font-size:17px}.productSeoContent p{font-size:14px;line-height:1.55}}';document.head.appendChild(st)}
  window.MirpanelSEO={BASE_URL:BASE,profiles:SEO,seoFor,productPath,productUrl,productIdFromPath,applyHomeSEO:homeSEO,applyProductSEO:productSEO,normalizeSlug:slug};
  function boot(){style();const id=productIdFromPath();id?setTimeout(()=>productSEO(id),0):homeSEO()}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();